ets_user_add:
    path:     /add
    defaults: { _controller: ETSUserBundle:Default:add }

ets_user_edit:
    path:     /edit
    defaults: { _controller: ETSUserBundle:Default:edit }
    
ets_user_private:
    path:     /private
    defaults: { _controller: ETSUserBundle:Default:private }
    
ets_restaurateur_add:
    path:     /addrestaurateur
    defaults: { _controller: ETSUserBundle:Restaurateur:add }
    
ets_restaurateur_edit:
    path:     /editrestaurateur/{restaurateur}
    defaults: { _controller: ETSUserBundle:Restaurateur:edit }
    
ets_restaurateur_delete:
    path:     /deleterestaurateur/{restaurateur}
    defaults: { _controller: ETSUserBundle:Restaurateur:delete }