parameters:
#    ets_user.example.class: ETS\UserBundle\Example

services:
#    ets_user.example:
#        class: %ets_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
