ets_restaurant_add:
    path:     /add
    defaults: { _controller: ETSRestaurantBundle:Default:add }
    
ets_restaurant_edit:
    path:     /edit/{restaurant}
    defaults: { _controller: ETSRestaurantBundle:Default:edit }

ets_restaurant_delete:
    path:     /delete/{restaurant}
    defaults: { _controller: ETSRestaurantBundle:Default:delete }
    
ets_restaurant_index:
    path:     /{restaurant}
    defaults: { _controller: ETSRestaurantBundle:Default:index }