<?php

namespace ETS\RestaurantBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{
    
    public function getAllRestaurants()
    {
      $query = $this->createQueryBuilder('a')
                    ->getQuery();

      return new Paginator($query);
    }
  
}
